routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('/projects', 'ProjectController')->except(['update', 'edit']);
    Route::get('/projects/{project}/posts/{post}', 'ProjectController@post');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Project extends Model
{
    protected $fillable = ['name', 'category', 'user_id'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function scopeListOwnedByUser($query)
    {
        return $query->where('user_id', Auth::user()->id)->get();
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Helpers\Visibility;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::listOwnedByUser();
        return view('pages.project.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Visibility::categories();

        return view('pages.project.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|min:3|unique:projects',
            'category' => 'required|integer',
        ]);
        $validated['user_id'] = Auth::user()->id;

        $project = Project::create($validated);

        return redirect("/projects/{$project->id}");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        $this->authorize('view', $project);

        $posts = collect(Visibility::posts());

        $posts = $posts->filter(function ($post) use ($project) {
            return in_array($project->category, $post['categories']);
        });

        $posts = $posts->map(function ($post) {
            $post['likes'] = Visibility::getPostLikes($post);
            return $post;
        });

        return view('pages.project.show', compact('posts', 'project'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        $this->authorize('delete', $project);

        $project->delete();

        return redirect('/projects');
    }

    /**
     * Get post data from visibility
     *
     * @param Project $project
     * @param int $postId
     * @return void
     */
    public function post(Project $project, $postId)
    {
        $posts = collect(Visibility::posts());

        $post = $posts->filter(function ($post) use ($project) {
            return in_array($project->category, $post['categories']);
        })->filter(function ($post) use ($postId) {
            return $post['id'] == $postId;
        })->first();

        $post['likes'] = Visibility::getPostLikes($post);

        return view('pages.project.post.show', compact('post', 'project'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @auth
                            <li><a class="nav-link" href="{{ route('projects.index') }}">{{ __('Projects') }}</a></li>
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/pages/project/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><a href="{{ route('projects.index') }}">Projekty</a> / @lang('New')</div>

                <div class="card-body ">
                    <form method="POST" action="{{ route('projects.index') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <select class="form-control" name="category" id="sel1">
                                    <option>@lang('Select category')</option>
                                    @foreach($categories as $category)
                                        <option value="{{ $category['id'] }}">{{ $category['name'] }}</option>                                    
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    @lang('Create')
                                </button>
                            </div>
                        </div>
                    </form>        
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/project/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Projekty</div>

                <div class="card-body text-right">
                    <a href="{{ route('projects.create') }}" class="btn btn-primary">@lang('Create')</a>
                    <table class="table text-left">
                        @forelse($projects as $project)
                            <tr>
                                <td>{{$project->name}}</td>
                                <td><a href="{{ route('projects.show', $project) }}">@lang('Open')</a></td>
                            </tr>
                        @empty
                            <tr>
                                <td>@lang('This collection is empty.')</td>
                            </tr>
                        @endforelse
                    </table>                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/project/post/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><a href="/projects">Projekty</a> / <a href="/projects/{{ $project->id }}">{{ $project->name }}</a> / {{ $post['title']['rendered'] }}</div>

                <div class="card-body">
                    <h2><a href="{{ $post['link'] }}" target="_blank">{{ $post['title']['rendered'] }}</a></h2>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>@lang('Facebook Likes')</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        @forelse($post['likes']->Facebook as $key => $like)
                            <tr>
                                <td>@lang($key)</td>
                                <td>{{ $like }}</td>
                            </tr>
                        @empty
                            empty
                        @endforelse 
                        </tbody>
                    </table>                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/project/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><a href="{{ route('projects.index') }}">Projekty</a> / {{ $project->name }}</div>

                <div class="card-body text-right">
                    <a class="btn btn-light" href="{{ route('projects.destroy', $project->id) }}" onclick="event.preventDefault(); var result = confirm('Naozaj chcete projekt vymazať?');
                            if (result) {
                                document.getElementById('destroy').submit();
                            }
                            ">
                        {{ __('Delete') }}
                    </a>

                    <form id="destroy" action="{{ route('projects.destroy', $project->id) }}" method="POST" style="display: none;">
                        @method('delete')
                        @csrf
                    </form>
                    <table class="table text-left">
                        @forelse($posts as $post)
                            <tr>
                            <td><a href="/projects/{{ $project->id }}/posts/{{ $post['id'] }}">{{ $post['link'] }}</a></td>
                            </tr>
                        @empty
                            <tr>
                                <td>@lang('This collection is empty.')</td>
                            </tr>
                        @endforelse 
                    </table>                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection